### ISSUE TITLE
No way to get it working on a linux machine

### ISSUE THREAD

**Issue by Gabri** [nicolay-zlobin/jesse-trades-info#1]
Hello,

I've tried installing on a vm with ubuntu 18.04.
I've had alittle issues during installations of packages but resolved searching on google.
Now building is working and when I run `npm run start` it starts successfully but when I try to go, on browser, in `http://localhost:3000/` I get this on console (and 500 on browser):
```
Making request to /api/files-list

 ERROR  ENOENT: no such file or directory, scandir 'uploads/'
  at Proxy.readdirSync (fs.js:981:3)
  at api/routes/files.js:51:6
  ...
```
Probably that forlder doesn't exists ..where do exactly I should create that folder?

thanks

**Comment by nicolay-zlobin** [comment]
@Gabri hello!

Fixed it. Try:

```
git pull
npm run build
npm run start
```

Feel free to contact me if you have any further questions.

**Comment by Gabri** [comment]
Thank you, now it works!
