### ISSUE TITLE
500 Error

### ISSUE THREAD

**Issue by erfansahaf** [nicolay-zlobin/jesse-trades-info#2]
When I try to upload the JSON file, I face with a `Request failed with status code 500` error. The console says nothing about it (same 500 error on the console). After refreshing the page, the running nuxt process prints the following error (just when the page is rendered on the server-side):

```
Making request to /api/read-file

 ERROR  orders.flat is not a function
  at asyncData (pages/trades/_backtest.vue:74:0)
  at process._tickCallback (internal/process/next_tick.js:68:7)
```

I have configured the database settings and all dependencies are installed via `npm run install` command. I gotta mention that the script is running outside the Jesse container on an Ubuntu 18.04 OS. The `Postgressql` port is also reachable via a telnet test.

**Comment by nicolay-zlobin** [comment]
Try to remove `node_modules` and `uploads` folders and reinstall dependencies with `npm install`. Then try to run it in dev mode `npm run dev`. Maybe in dev mode, it will show a more explicit message.

Which version of Node do you have? Mine is v12.18.1.
Can you provide an example of a JSON file with which the error occurs?

**Comment by erfansahaf** [comment]
The problem was Postgresql security rules. Closing.
