### ISSUE TITLE
Supporting other timeframes

### ISSUE THREAD

**Issue by erfansahaf** [nicolay-zlobin/jesse-trades-info#3]
![image](https://user-images.githubusercontent.com/12012168/97303016-118fb800-186f-11eb-9f0a-b2b16fabccba.png)

As you can see, the chart shows 1h candles but my trades were made in 15m timeframe. In my case, both buy and sell orders are marked on a single 1h candle at the beginning of the day.

Is there any plan for supporting other timeframes on the Chart?

**Comment by nicolay-zlobin** [comment]
I'm batching candles into a bigger one for performance sake, depending on how big a backtest is. You can see it here:

https://github.com/nicolay-zlobin/jesse-trades-info/blob/85e50cbcda9adb0748252fccaabced53e34dfb02/api/routes/candles.js#L49

Try a smaller range of a backtest, and you will see smaller candles. 
I'll think about the ability to switch candles and redraw the chart.

**Comment by erfansahaf** [comment]
I'm thinking about something like you said. It would be better if we draw candles when their time is in the viewport with their original timeframe.

What's the chart library that you've used in this project? Does it support such behavior or we have to remove the chart element completely from DOM?

**Comment by nicolay-zlobin** [comment]
There is no actual timeframe property inside Jesse's JSON file. Besides, some strategies have several routes with different candles sizes.

Yes, lightweight-charts supports range switcher. You can see an example here: https://jsfiddle.net/TradingView/qrb9a850/.

I'll consider implementing this feature in the next updates. Thanks for proposing it.

**Comment by nicolay-zlobin** [comment]
@erfansahaf hey! I uploaded the range switcher in the develop branch. See the left part of the chart. You can try it before the official release. Don't forget `npm install`.

<img width="960" alt="image" src="https://user-images.githubusercontent.com/25667028/100226135-5bcc8d80-2f30-11eb-958e-3f8fed25bc92.png">

**Comment by erfansahaf** [comment]
@nicolay-zlobin Hey Nicolay! Sorry for the late response.

I'm currently a bit busy because of a project but I will get back to you as soon I find free time to test this. Thanks for your effort!
