### ISSUE TITLE
Request failed with status code 500

### ISSUE THREAD

**Issue by DrrMrr** [nicolay-zlobin/jesse-trades-info#8]
Hi, 

your tool seems very useful, but I receive error "Request failed with status code 500". 

Please se the link https://ibb.co/vj4mrSJ . I get an error every time I click on uploaded Backtest. 

Am I missing something or have I forgot to setup something?

Thank you

**Comment by nicolay-zlobin** [comment]
@DrrMrr hey! I know there's a problem with identifying error messages. I propose the issue related to a database connection. Check the `.env` file whether DB params correct there or not. I'm going to fix it in the next release.

**Comment by DrrMrr** [comment]
> Hi, 
> 
> 
> 
> your tool seems very useful, but I receive error "Request failed with status code 500". 
> 
> 
> 
> Please se the link https://ibb.co/vj4mrSJ . I get an error every time I click on uploaded Backtest. 
> 
> 
> 
> Am I missing something or have I forgot to setup something?
> 
> 
> 
> Thank you

Hi, 

it was a problem, because I didn't reneme the .env file.

Sorry and best regards

**Comment by nicolay-zlobin** [comment]
Fixed with v0.2.0 release
